module.exports = [
    {
    name: 'Berty',
    img: 'https://static.independent.co.uk/s3fs-public/thumbnails/image/2020/02/04/10/detective-dog.jpg?quality=75&width=982&height=726&auto=webp',
    gender: 'male',
    breed: 'golden retriever',
    age: '2',
    personality: 'happy-go-lucky, friendly, patient',
    energy: 3,
    about: 'Good with kids and other dogs.  Loves to play fetch.  Is usually well behaved (unless sandwhich meat slices are involved then he\'s a monster',
    locations: 'parks (especially those with squirrels), hiking trails, parks with open fields',
    },
    {
    name: 'Queen Dumples',
    img: 'https://www.thesprucepets.com/thmb/Kh-xt27-hqeQzhyr9288cl_P64I=/1396x1396/smart/filters:no_upscale()/twenty20_f84c633e-705e-4bf8-a724-00cdea750d8d-590b51893df78c92837b18d6.jpg',
    gender: 'female',
    breed: 'Chihuahua',
    age: 6,
    personality: 'High energy, high maintenance, thinks she\'s a big dog',
    energy: 5,
    about: 'Loves hanging out with bigger dogs, will get aggressive if she thinks she is being underestimated',
    locations: 'local parks, dog parks, dog-friendly playgrouns',
    },
    {
    name: 'Bandit',
    img: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSC1EjY8RdwAWf9vhzK9p37jM8mofOAOv4k-z2SPIcgB2tNlgcgT5dg5pmNZ1TYl-j0IsQ&usqp=CAU',
    gender: 'male',
    breed: 'American Eskimo',
    age: 7,
    personality: 'bossy, playful',
    energy: 4,
    about: 'Loves dog companionship!  He does sometimes nip at larger dogs to try and prove himself, but has no problem being put in his place',
    locations: 'dog parks',
    },
    {
    name: 'Sombra',
    img: 'https://moderndogmagazine.com/sites/default/files/images/breeds/top_images/border-collie-987947_1920.jpg',
    gender: 'female',
    breed: 'border collie',
    age: 3,
    personality: "playful, friendly, social",
    energy: 5,
    about: 'Loves to race and play, usually accepting of other dogs (with the acception of ',
    locations: 'nature trails, hiking location, anywhere with water',
    },
    {
    name: 'Cher',
    img: 'https://upload.wikimedia.org/wikipedia/commons/thumb/6/6b/IMGP0988_Vasilissa060423.jpg/150px-IMGP0988_Vasilissa060423.jpg',
    gender: 'female',
    breed: "silk haired saluki",
    age: 3,
    personality: 'low-key, laid back, mostly-friendly',
    energy: 2,
    about: 'Cher enjoys mostly older or laid-back dogs, aside from running she prefers low-key companionable play over romping',
    locations: 'parks, doggy spas, greenway',
    },
    {
    name: 'Jabbu Jabba',
    img: 'https://cdn.britannica.com/05/30105-004-644BE36D.jpg',
    gender: 'Male',
    breed: 'bulldog',
    age: 3,
    personality: "calm, laid back, friendly, gets short with hyper energetic dogs",
    energy: 1,
    about: 'Jabbu was the runt of his litter, and tends to be laid back about everything.  Good around kids and other animals, but not hyper dogs',
    locations: 'dog parks, lakes (especially with his floaty',
    },
    {
    name: 'Meep',
    img: 'https://cdn.wamiz.fr/cdn-cgi/image/quality=80,width=400,height=400,fit=cover/animal/breed/pictures/61a8a1e3c9eb1148119899.jpg',
    gender: 'female',
    breed: 'bull terrier',
    age: 6,
    personality: 'well-mannered, obedient, playful',
    energy: 3,
    about: 'Meep loves smaller dogs, not sure why.  She is very respectful toward other dogs but really comes alive around smaller pups',
    locations: 'dog parks, greenways',
    },
    {
    name: 'Cat',
    img: 'https://www.zooplus.co.uk/magazine/wp-content/uploads/2018/07/basenji.jpg',
    gender: 'male',
    breed: 'Basenji',
    age: 1,
    personality: 'weirdo, playful, friendly',
    energy: 4,
    about: 'Cat, yes a dog named Cat, loves being around all animals especially cats!  He tends to like playing with people more than dogs but clicks with dogs that are more cat sized',
    locations: 'dog park, trails',
    },
    {
    name: 'Cleopatra',
    img: 'https://images.unsplash.com/photo-1617895153857-82fe79adfcd4?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxleHBsb3JlLWZlZWR8MXx8fGVufDB8fHx8&w=1000&q=80',
    gender: 'female',
    breed: 'siberian husky',
    age: '6 months',
    personality: 'playful, intense',
    energy: 4,
    about: 'Cleo really really love playmates!  Big dogs, little dogs, fellow puppies, humans; she will even just play by herself.  Loves doggy daycare, but prefers less fenced in areas',
    locations: "nature trails, hiking, places with water, dog parks, dog-friendly parks, greenways",
    },
    {
    name: 'Mr. Noodles',
    img: 'https://geniusvets.s3.amazonaws.com/gv-dog-breeds/chinese-shar-pei-1.jpg',
    gender: 'male',
    breed: 'shar-pei',
    age: '2',
    personality: 'friendly, somewhat territorial(esp with snacks), playful',
    energy: 3,
    about: 'Enjoys competing to fetch balls and sticks, will romp in general so long as he doesn\'t have to get messy (hates mud)',
    locations: 'Dog parks, greenways, pakrs with fields',
    },
];